### ISSUE TITLE
Kubuntu, but no ethernet 

### ISSUE THREAD

**Issue by Taddaeus** [marcosfad/mbp-ubuntu#101]
I am very pleased that Kubuntu is now supported!
However, I do not even have Ethernet with my Macbook Pro 13" 2018 touchbar - tried with Kubuntu 23.10 v6.5.7-2 and v6.5.8-1.
Surely this should work directly? Or are the extra steps for WIFI (don't need it and didn't set it up) needed for Ethernet as well?

Or am I missing something?

**Comment by AdityaGarg8** [comment]
Does your ethernet adapter work with other Linux PCs?

**Comment by Taddaeus** [comment]
Hi
Yes. In addition, I have tried 4 different ones.
However, a connection must be active, because time and date are correct - I did not set them manually.
I tried ping: command not found.
The “TaskManager” does not show any network activity.
Also no audio and no keyboard backlight...

**Comment by AdityaGarg8** [comment]
Can you share your `journalctl -k`. You could you a service like pastebin for that

**Comment by Taddaeus** [comment]
You can find it here:

 https://privatebin.at/?0c7038f870f5283b#5LVqfoRt4cdKCH8ZNTmpEgpWD6LByKmgfkpNDYbpewCp <https://privatebin.at/?0c7038f870f5283b#5LVqfoRt4cdKCH8ZNTmpEgpWD6LByKmgfkpNDYbpewCp>

PW: Taddaeus

Thanks for investigate

**Comment by AdityaGarg8** [comment]
It’s asking for password

**Comment by Taddaeus** [comment]
PW: Taddaeus
 
sorry, should have done without password..
