### ISSUE TITLE
Ubuntu Server

### ISSUE THREAD

**Issue by webysther** [marcosfad/mbp-ubuntu#102]
Hi, any chance to add ubuntu server to github worflow?

Alternativelly I remove the desktop after install:

```sh
sudo apt-get purge ubuntu-desktop
sudo apt autoremove
```

**Comment by AdityaGarg8** [comment]
There are no plans to add Ubuntu server. If someone wants to maintain it, either open a PR or create your fork

I am not very sure what removing ubuntu-desktop does, try at your own risk.
