### ISSUE TITLE
Can't install the latest release

### ISSUE THREAD

**Issue by Rom888** [marcosfad/mbp-ubuntu#103]
I tried to install the latest version:
ubuntu-23.10-6.5.8-t2-mantic.zip

After selecting "Install" or "Try" I only see a flashing screen with:
```
BCMDHD_ExitbootService: Enter
dhd_os_wifi_platform...
dhd_os_wifi_platform...
```
pc:
```
macbook pro, 16 inch, 2019
model identifier: MacBookPro16.1
Intel Core i9 2.3g
Intel UHD graphics 630
AMD radeon pro 5500M
```

**Comment by AdityaGarg8** [comment]
Which software are you using to burn the iso?

**Comment by Rom888** [comment]
Under Ubuntu Linux on the another machine:

sudo dd if=/tmp/ubuntu-23.10-6.5.8-t2-mantic.iso of=/dev/sdb bs=4M status=progress oflag=sync

**Comment by AdityaGarg8** [comment]
Try using balena etcher

**Comment by Rom888** [comment]
Thank you, tried, but without success 
![Screenshot from 2023-10-23 12-21-27](https://github.com/t2linux/T2-Ubuntu/assets/36224737/2466980c-1da4-473a-9119-e774f98807e5)

**Comment by Rom888** [comment]
I have installed apple-set-os loader.
Could this be the reason?

**Comment by AdityaGarg8** [comment]
Seems to be some issue with your USB

**Comment by Rom888** [comment]
I tried with another USB, and the same result.
Also the Ubuntu Startup Disk Creator doesn't accept this ISO.

**Comment by AdityaGarg8** [comment]
Try burning using macOS

**Comment by Rom888** [comment]
After rebooting into macOS everything is fine with the same USB.
It looks like it was because
nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00

**Comment by AdityaGarg8** [comment]
Possible

**Comment by Sprunglicious** [comment]
I have experienced the issue in the past on my MacbookPro15,1. Use the Ventoy ("https://ventoy.net/en/download.html") utility. I have never had an issue since I begun to use the utility. These two models are pretty close in specification if I remember right.
