### ISSUE TITLE
Unable to use firmware.sh on old macOS

### ISSUE THREAD

**Issue by irenatorosyan** [marcosfad/mbp-ubuntu#104]
My computer is running macOS Mojave Version 10.14.6. Unfortunately, as I already partitioned my disk for Ubuntu, I am unable to update to later versions of macOS to be able to run the script. I am not sure if this is of any help, but I also have a mac on M2 chip running macOS Sonoma. Is there a way to use the arm computer or somehow run the script on older version of macOS?

**Comment by lemmyg** [comment]
If your computer a new arm. You should try https://asahilinux.org This project is for old Macs with T2 chip.

**Comment by AdityaGarg8** [comment]
> My computer is running macOS Mojave Version 10.14.6. Unfortunately, as I already partitioned my disk for Ubuntu, I am unable to update to later versions of macOS to be able to run the script. I am not sure if this is of any help, but I also have a mac on M2 chip running macOS Sonoma. Is there a way to use the arm computer or somehow run the script on older version of macOS?

https://github.com/AdityaGarg8/Apple-Firmware/releases/download/Ventura/apple-firmware.deb

Install this deb and WiFi should start working.,

**Comment by irenatorosyan** [comment]
> > My computer is running macOS Mojave Version 10.14.6. Unfortunately, as I already partitioned my disk for Ubuntu, I am unable to update to later versions of macOS to be able to run the script. I am not sure if this is of any help, but I also have a mac on M2 chip running macOS Sonoma. Is there a way to use the arm computer or somehow run the script on older version of macOS?
> 
> https://github.com/AdityaGarg8/Apple-Firmware/releases/download/Ventura/apple-firmware.deb
> 
> Install this deb and WiFi should start working.,

Thank you for the suggestion! Just tried it out but I doesn't seem to work for me unfortunately.

**Comment by irenatorosyan** [comment]
> If your computer a new arm. You should try https://asahilinux.org This project is for old Macs with T2 chip.

I have ubuntu on my old mac with T2. Just thought the new one may be helpful to fix the issues. Currently not trying to run Ubuntu on arm but I'll remember the advice for the future. Thank you!

**Comment by AdityaGarg8** [comment]
> > > My computer is running macOS Mojave Version 10.14.6. Unfortunately, as I already partitioned my disk for Ubuntu, I am unable to update to later versions of macOS to be able to run the script. I am not sure if this is of any help, but I also have a mac on M2 chip running macOS Sonoma. Is there a way to use the arm computer or somehow run the script on older version of macOS?
> > 
> > 
> > https://github.com/AdityaGarg8/Apple-Firmware/releases/download/Ventura/apple-firmware.deb
> > Install this deb and WiFi should start working.,
> 
> Thank you for the suggestion! Just tried it out but I doesn't seem to work for me unfortunately.

After installing this, what's 

1. `ls /lib/firmware/brcm`
2. `journalctl -k --grep=brcmfmac`

**Comment by irenatorosyan** [comment]
> > > > My computer is running macOS Mojave Version 10.14.6. Unfortunately, as I already partitioned my disk for Ubuntu, I am unable to update to later versions of macOS to be able to run the script. I am not sure if this is of any help, but I also have a mac on M2 chip running macOS Sonoma. Is there a way to use the arm computer or somehow run the script on older version of macOS?
> > > 
> > > 
> > > https://github.com/AdityaGarg8/Apple-Firmware/releases/download/Ventura/apple-firmware.deb
> > > Install this deb and WiFi should start working.,
> > 
> > 
> > Thank you for the suggestion! Just tried it out but I doesn't seem to work for me unfortunately.
> 
> After installing this, what's
> 
>     1. `ls /lib/firmware/brcm`
> 
>     2. `journalctl -k --grep=brcmfmac`

Here's the output

brleude@brleude:~$ ls /lib/firmware/brcm
 BCM-0a5c-6410.hcd.zst
 BCM-0bb4-0306.hcd.zst
 bcm4329-fullmac-4.bin.zst
 bcm43xx-0.fw.zst
 bcm43xx_hdr-0.fw.zst
 brcmbt4377b3-apple,formosa.bin
 brcmbt4377b3-apple,formosa.ptb
 brcmbt4378b1-apple,atlantisb-m.bin
 brcmbt4378b1-apple,atlantisb-m.ptb
 brcmbt4378b1-apple,atlantisb-u.bin
 brcmbt4378b1-apple,atlantisb-u.ptb
 brcmbt4378b1-apple,capri-m.bin
 brcmbt4378b1-apple,capri-m.ptb
 brcmbt4378b1-apple,capri-u.bin
 brcmbt4378b1-apple,capri-u.ptb
 brcmbt4378b1-apple,honshu-m.bin
 brcmbt4378b1-apple,honshu-m.ptb
 brcmbt4378b1-apple,honshu-u.bin
 brcmbt4378b1-apple,honshu-u.ptb
 brcmbt4378b1-apple,santorini-m.bin
 brcmbt4378b1-apple,santorini-m.ptb
 brcmbt4378b1-apple,santorini-u.bin
 brcmbt4378b1-apple,santorini-u.ptb
 brcmbt4378b1-apple,shikoku-m.bin
 brcmbt4378b1-apple,shikoku-m.ptb
 brcmbt4378b1-apple,shikoku-u.bin
 brcmbt4378b1-apple,shikoku-u.ptb
 brcmbt4378b3-apple,kyushu-u.bin
 brcmbt4378b3-apple,kyushu-u.ptb
 brcmbt4387c2-apple,hokkaido-u.bin
 brcmbt4387c2-apple,hokkaido-u.ptb
 brcmbt4387c2-apple,madagascar-u.bin
 brcmbt4387c2-apple,madagascar-u.ptb
 brcmbt4387c2-apple,maldives-u.bin
 brcmbt4387c2-apple,maldives-u.ptb
 brcmbt4387c2-apple,okinawa-u.bin
 brcmbt4387c2-apple,okinawa-u.ptb
 brcmfmac43012-sdio.bin.zst
 brcmfmac43012-sdio.clm_blob.zst
 brcmfmac43143-sdio.bin.zst
 brcmfmac43143.bin.zst
 brcmfmac43236b.bin.zst
 brcmfmac43241b0-sdio.bin.zst
 brcmfmac43241b4-sdio.Advantech-MICA-071.txt.zst
'brcmfmac43241b4-sdio.Intel Corp.-VALLEYVIEW C0 PLATFORM.txt.zst'
 brcmfmac43241b4-sdio.bin.zst
 brcmfmac43241b5-sdio.bin.zst
 brcmfmac43242a.bin.zst
 brcmfmac4329-sdio.bin.zst
 brcmfmac4330-sdio.Prowise-PT301.txt.zst
 brcmfmac4330-sdio.bin.zst
 brcmfmac4334-sdio.bin.zst
'brcmfmac43340-sdio.ASUSTeK COMPUTER INC.-TF103CE.txt.zst'
 brcmfmac43340-sdio.bin.zst
 brcmfmac43340-sdio.meegopad-t08.txt.zst
 brcmfmac43340-sdio.pov-tab-p1006w-data.txt.zst
 brcmfmac43340-sdio.predia-basic.txt.zst
 brcmfmac4335-sdio.bin.zst
 brcmfmac43362-sdio.WC121.txt.zst
 brcmfmac43362-sdio.bin.zst
 brcmfmac43362-sdio.cubietech,cubietruck.txt.zst
 brcmfmac43362-sdio.kobo,aura.txt.zst
 brcmfmac43362-sdio.kobo,tolino-shine2hd.txt.zst
 brcmfmac43362-sdio.lemaker,bananapro.txt.zst
 brcmfmac4339-sdio.bin.zst
 brcmfmac43430-sdio.AP6212.txt.zst
 brcmfmac43430-sdio.Hampoo-D2D3_Vi8A1.txt.zst
 brcmfmac43430-sdio.MUR1DX.txt.zst
 brcmfmac43430-sdio.beagle,beaglev-starlight-jh7100-a1.txt.zst
 brcmfmac43430-sdio.beagle,beaglev-starlight-jh7100-r0.txt.zst
 brcmfmac43430-sdio.bin.zst
 brcmfmac43430-sdio.clm_blob.zst
 brcmfmac43430-sdio.friendlyarm,nanopi-r1.txt.zst
 brcmfmac43430-sdio.raspberrypi,3-model-b.txt.zst
 brcmfmac43430-sdio.raspberrypi,model-zero-2-w.txt.zst
 brcmfmac43430-sdio.raspberrypi,model-zero-w.txt.zst
 brcmfmac43430-sdio.sinovoip,bpi-m2-plus.txt.zst
 brcmfmac43430-sdio.sinovoip,bpi-m2-ultra.txt.zst
 brcmfmac43430-sdio.sinovoip,bpi-m2-zero.txt.zst
 brcmfmac43430-sdio.sinovoip,bpi-m3.txt.zst
 brcmfmac43430-sdio.starfive,visionfive-v1.txt.zst
'brcmfmac43430a0-sdio.ONDA-V80 PLUS.txt.zst'
 brcmfmac43430a0-sdio.bin.zst
 brcmfmac43430a0-sdio.ilife-S806.txt.zst
 brcmfmac43430a0-sdio.jumper-ezpad-mini3.txt.zst
 brcmfmac43455-sdio.AW-CM256SM.txt.zst
'brcmfmac43455-sdio.MINIX-NEO Z83-4.txt.zst'
'brcmfmac43455-sdio.Raspberry Pi Foundation-Raspberry Pi 4 Model B.txt.zst'
'brcmfmac43455-sdio.Raspberry Pi Foundation-Raspberry Pi Compute Module 4.txt.zst'
 brcmfmac43455-sdio.acepc-t8.txt.zst
 brcmfmac43455-sdio.beagle,am5729-beagleboneai.txt.zst
 brcmfmac43455-sdio.bin.zst
 brcmfmac43455-sdio.clm_blob.zst
 brcmfmac43455-sdio.pine64,pinebook-pro.txt.zst
 brcmfmac43455-sdio.pine64,pinenote-v1.1.txt.zst
 brcmfmac43455-sdio.pine64,pinenote-v1.2.txt.zst
 brcmfmac43455-sdio.pine64,pinephone-pro.txt.zst
 brcmfmac43455-sdio.pine64,quartz64-a.txt.zst
 brcmfmac43455-sdio.pine64,quartz64-b.txt.zst
 brcmfmac43455-sdio.pine64,rockpro64-v2.0.txt.zst
 brcmfmac43455-sdio.pine64,rockpro64-v2.1.txt.zst
 brcmfmac43455-sdio.pine64,soquartz-blade.txt.zst
 brcmfmac43455-sdio.pine64,soquartz-cm4io.txt.zst
 brcmfmac43455-sdio.pine64,soquartz-model-a.txt.zst
 brcmfmac43455-sdio.raspberrypi,3-model-a-plus.txt.zst
 brcmfmac43455-sdio.raspberrypi,3-model-b-plus.txt.zst
 brcmfmac43455-sdio.raspberrypi,4-model-b.txt.zst
 brcmfmac4350-pcie.bin.zst
 brcmfmac4350c2-pcie.bin.zst
 brcmfmac4354-sdio.bin.zst
 brcmfmac4354-sdio.clm_blob.zst
'brcmfmac4356-pcie.Intel Corporation-CHERRYVIEW D1 PLATFORM.txt.zst'
'brcmfmac4356-pcie.Xiaomi Inc-Mipad2.txt.zst'
 brcmfmac4356-pcie.bin.zst
 brcmfmac4356-pcie.clm_blob.zst
 brcmfmac4356-pcie.gpd-win-pocket.txt.zst
 brcmfmac4356-sdio.AP6356S.txt.zst
 brcmfmac4356-sdio.bin.zst
 brcmfmac4356-sdio.clm_blob.zst
 brcmfmac4356-sdio.firefly,firefly-rk3399.txt.zst
 brcmfmac4356-sdio.khadas,vim2.txt.zst
 brcmfmac4356-sdio.vamrs,rock960.txt.zst
 brcmfmac43569.bin.zst
 brcmfmac43570-pcie.bin.zst
 brcmfmac43570-pcie.clm_blob.zst
 brcmfmac4358-pcie.bin.zst
 brcmfmac43602-pcie.ap.bin.zst
 brcmfmac43602-pcie.bin.zst
 brcmfmac4364b2-pcie.apple,ekans-HRPN-m-5.1.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-m-6.1.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-m-6.3.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-m-7.1.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-m-7.3.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-m-7.5.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-m-7.7.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-u-1.1.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-u-6.1.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-u-7.1.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-u-7.3.txt
 brcmfmac4364b2-pcie.apple,ekans-HRPN-u-7.5.txt
 brcmfmac4364b2-pcie.apple,ekans.bin
 brcmfmac4364b2-pcie.apple,ekans.clm_blob
 brcmfmac4364b2-pcie.apple,ekans.txcap_blob
 brcmfmac4364b2-pcie.apple,hanauma-HRPN-m.txt
 brcmfmac4364b2-pcie.apple,hanauma-HRPN-u.txt
 brcmfmac4364b2-pcie.apple,hanauma.bin
 brcmfmac4364b2-pcie.apple,hanauma.clm_blob
 brcmfmac4364b2-pcie.apple,hanauma.txcap_blob
 brcmfmac4364b2-pcie.apple,kahana-HRPN-m.txt
 brcmfmac4364b2-pcie.apple,kahana-HRPN-u.txt
 brcmfmac4364b2-pcie.apple,kahana.bin
 brcmfmac4364b2-pcie.apple,kahana.clm_blob
 brcmfmac4364b2-pcie.apple,kahana.txcap_blob
 brcmfmac4364b2-pcie.apple,kauai-HRPN-m-6.1.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-m-6.3.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-m-7.1.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-m-7.3.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-m-7.5.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-m-7.7.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-u-6.1.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-u-7.1.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-u-7.3.txt
 brcmfmac4364b2-pcie.apple,kauai-HRPN-u-7.5.txt
 brcmfmac4364b2-pcie.apple,kauai.bin
 brcmfmac4364b2-pcie.apple,kauai.clm_blob
 brcmfmac4364b2-pcie.apple,kauai.txcap_blob
 brcmfmac4364b2-pcie.apple,lanai-HRPN-m.txt
 brcmfmac4364b2-pcie.apple,lanai-HRPN-u.txt
 brcmfmac4364b2-pcie.apple,lanai.bin
 brcmfmac4364b2-pcie.apple,lanai.clm_blob
 brcmfmac4364b2-pcie.apple,lanai.txcap_blob
 brcmfmac4364b2-pcie.apple,maui-HRPN-m-6.1.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-m-6.3.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-m-7.1.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-m-7.3.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-m-7.5.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-m-7.7.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-u-6.1.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-u-7.1.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-u-7.3.txt
 brcmfmac4364b2-pcie.apple,maui-HRPN-u-7.5.txt
 brcmfmac4364b2-pcie.apple,maui.bin
 brcmfmac4364b2-pcie.apple,maui.clm_blob
 brcmfmac4364b2-pcie.apple,maui.txcap_blob
 brcmfmac4364b2-pcie.apple,midway-HRPN-m.txt
 brcmfmac4364b2-pcie.apple,midway-HRPN-u.txt
 brcmfmac4364b2-pcie.apple,midway.bin
 brcmfmac4364b2-pcie.apple,midway.clm_blob
 brcmfmac4364b2-pcie.apple,midway.txcap_blob
 brcmfmac4364b2-pcie.apple,nihau-HRPN-m.txt
 brcmfmac4364b2-pcie.apple,nihau-HRPN-u.txt
 brcmfmac4364b2-pcie.apple,nihau.bin
 brcmfmac4364b2-pcie.apple,nihau.clm_blob
 brcmfmac4364b2-pcie.apple,nihau.txcap_blob
 brcmfmac4364b2-pcie.apple,sid-HRPN-m-7.5.txt
 brcmfmac4364b2-pcie.apple,sid-HRPN-m-7.7.txt
 brcmfmac4364b2-pcie.apple,sid-HRPN-u.txt
 brcmfmac4364b2-pcie.apple,sid.bin
 brcmfmac4364b2-pcie.apple,sid.clm_blob
 brcmfmac4364b2-pcie.apple,sid.txcap_blob
 brcmfmac4364b3-pcie.apple,bali-HRPN-m.txt
 brcmfmac4364b3-pcie.apple,bali-HRPN-u.txt
 brcmfmac4364b3-pcie.apple,bali.bin
 brcmfmac4364b3-pcie.apple,bali.clm_blob
 brcmfmac4364b3-pcie.apple,bali.txcap_blob
 brcmfmac4364b3-pcie.apple,borneo-HRPN-m.txt
 brcmfmac4364b3-pcie.apple,borneo-HRPN-u-7.7.txt
 brcmfmac4364b3-pcie.apple,borneo-HRPN-u-7.9.txt
 brcmfmac4364b3-pcie.apple,borneo.bin
 brcmfmac4364b3-pcie.apple,borneo.clm_blob
 brcmfmac4364b3-pcie.apple,borneo.txcap_blob
 brcmfmac4364b3-pcie.apple,hanauma-HRPN-m.txt
 brcmfmac4364b3-pcie.apple,hanauma-HRPN-u.txt
 brcmfmac4364b3-pcie.apple,hanauma.bin
 brcmfmac4364b3-pcie.apple,hanauma.clm_blob
 brcmfmac4364b3-pcie.apple,hanauma.txcap_blob
 brcmfmac4364b3-pcie.apple,kahana-HRPN-m.txt
 brcmfmac4364b3-pcie.apple,kahana-HRPN-u.txt
 brcmfmac4364b3-pcie.apple,kahana.bin
 brcmfmac4364b3-pcie.apple,kahana.clm_blob
 brcmfmac4364b3-pcie.apple,kahana.txcap_blob
 brcmfmac4364b3-pcie.apple,kure-HRPN-m.txt
 brcmfmac4364b3-pcie.apple,kure-HRPN-u.txt
 brcmfmac4364b3-pcie.apple,kure.bin
 brcmfmac4364b3-pcie.apple,kure.clm_blob
 brcmfmac4364b3-pcie.apple,kure.txcap_blob
 brcmfmac4364b3-pcie.apple,sid-HRPN-m.txt
 brcmfmac4364b3-pcie.apple,sid-HRPN-u.txt
 brcmfmac4364b3-pcie.apple,sid.bin
 brcmfmac4364b3-pcie.apple,sid.clm_blob
 brcmfmac4364b3-pcie.apple,sid.txcap_blob
 brcmfmac4364b3-pcie.apple,trinidad-HRPN-m.txt
 brcmfmac4364b3-pcie.apple,trinidad-HRPN-u.txt
 brcmfmac4364b3-pcie.apple,trinidad.bin
 brcmfmac4364b3-pcie.apple,trinidad.clm_blob
 brcmfmac4364b3-pcie.apple,trinidad.txcap_blob
 brcmfmac4366b-pcie.bin.zst
 brcmfmac4366c-pcie.bin.zst
 brcmfmac4371-pcie.bin.zst
 brcmfmac4373-sdio.bin.zst
 brcmfmac4373-sdio.clm_blob.zst
 brcmfmac4373.bin.zst
 brcmfmac4377b3-pcie.apple,fiji-SPPR-m.txt
 brcmfmac4377b3-pcie.apple,fiji-SPPR-u.txt
 brcmfmac4377b3-pcie.apple,fiji.bin
 brcmfmac4377b3-pcie.apple,fiji.clm_blob
 brcmfmac4377b3-pcie.apple,fiji.txcap_blob
 brcmfmac4377b3-pcie.apple,formosa-SPPR-m.txt
 brcmfmac4377b3-pcie.apple,formosa-SPPR-u.txt
 brcmfmac4377b3-pcie.apple,formosa.bin
 brcmfmac4377b3-pcie.apple,formosa.clm_blob
 brcmfmac4377b3-pcie.apple,formosa.txcap_blob
 brcmfmac4377b3-pcie.apple,tahiti-SPPR-m.txt
 brcmfmac4377b3-pcie.apple,tahiti-SPPR-u.txt
 brcmfmac4377b3-pcie.apple,tahiti.bin
 brcmfmac4377b3-pcie.apple,tahiti.clm_blob
 brcmfmac4377b3-pcie.apple,tahiti.txcap_blob
 brcmfmac4378b1-pcie.apple,atlantisb-RASP-m.txt
 brcmfmac4378b1-pcie.apple,atlantisb-RASP-u.txt
 brcmfmac4378b1-pcie.apple,atlantisb.bin
 brcmfmac4378b1-pcie.apple,atlantisb.clm_blob
 brcmfmac4378b1-pcie.apple,atlantisb.txcap_blob
 brcmfmac4378b1-pcie.apple,capri-RASP-m.txt
 brcmfmac4378b1-pcie.apple,capri-RASP-u.txt
 brcmfmac4378b1-pcie.apple,capri.bin
 brcmfmac4378b1-pcie.apple,capri.clm_blob
 brcmfmac4378b1-pcie.apple,capri.txcap_blob
 brcmfmac4378b1-pcie.apple,honshu-RASP-m.txt
 brcmfmac4378b1-pcie.apple,honshu-RASP-u.txt
 brcmfmac4378b1-pcie.apple,honshu.bin
 brcmfmac4378b1-pcie.apple,honshu.clm_blob
 brcmfmac4378b1-pcie.apple,honshu.txcap_blob
 brcmfmac4378b1-pcie.apple,kyushu.bin
 brcmfmac4378b1-pcie.apple,kyushu.clm_blob
 brcmfmac4378b1-pcie.apple,kyushu.txcap_blob
 brcmfmac4378b1-pcie.apple,kyushu.txt
 brcmfmac4378b1-pcie.apple,santorini-RASP-m.txt
 brcmfmac4378b1-pcie.apple,santorini-RASP-u.txt
 brcmfmac4378b1-pcie.apple,santorini.bin
 brcmfmac4378b1-pcie.apple,santorini.clm_blob
 brcmfmac4378b1-pcie.apple,santorini.txcap_blob
 brcmfmac4378b1-pcie.apple,shikoku-RASP-m.txt
 brcmfmac4378b1-pcie.apple,shikoku-RASP-u.txt
 brcmfmac4378b1-pcie.apple,shikoku.bin
 brcmfmac4378b1-pcie.apple,shikoku.clm_blob
 brcmfmac4378b1-pcie.apple,shikoku.txcap_blob
 brcmfmac4378b3-pcie.apple,kyushu.bin
 brcmfmac4378b3-pcie.apple,kyushu.clm_blob
 brcmfmac4378b3-pcie.apple,kyushu.txcap_blob
 brcmfmac4378b3-pcie.apple,kyushu.txt
 brcmfmac4387c2-pcie.apple,hokkaido.bin
 brcmfmac4387c2-pcie.apple,hokkaido.clm_blob
 brcmfmac4387c2-pcie.apple,hokkaido.txcap_blob
 brcmfmac4387c2-pcie.apple,hokkaido.txt
 brcmfmac4387c2-pcie.apple,madagascar.bin
 brcmfmac4387c2-pcie.apple,madagascar.clm_blob
 brcmfmac4387c2-pcie.apple,madagascar.txcap_blob
 brcmfmac4387c2-pcie.apple,madagascar.txt
 brcmfmac4387c2-pcie.apple,maldives.bin
 brcmfmac4387c2-pcie.apple,maldives.clm_blob
 brcmfmac4387c2-pcie.apple,maldives.txcap_blob
 brcmfmac4387c2-pcie.apple,maldives.txt
 brcmfmac4387c2-pcie.apple,okinawa.bin
 brcmfmac4387c2-pcie.apple,okinawa.clm_blob
 brcmfmac4387c2-pcie.apple,okinawa.txcap_blob
 brcmfmac4387c2-pcie.apple,okinawa.txt
 brcmfmac54591-pcie.clm_blob.zst
 brcmfmac89459-pcie.apple,hawaii-YSBC-m-2.3.txt
 brcmfmac89459-pcie.apple,hawaii-YSBC-m-2.5.txt
 brcmfmac89459-pcie.apple,hawaii-YSBC-u-4.1.txt
 brcmfmac89459-pcie.apple,hawaii-YSBC-u-4.3.txt
 brcmfmac89459-pcie.apple,hawaii.bin
 brcmfmac89459-pcie.apple,hawaii.clm_blob
 brcmfmac89459-pcie.apple,hawaii.txcap_blob
brleude@brleude:~$ journalctl -k --grep=brcmfmac
Nov 28 21:57:11 brleude kernel: usbcore: registered new interface driver brcmfm>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: enabling device (0000 ->>
Nov 28 21:57:11 brleude kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/br>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for>
Nov 28 21:57:11 brleude kernel: brcmfmac 0000:02:00.0: brcmf_pcie_setup: Dongle>
lines 1-11/11 (END)

**Comment by AdityaGarg8** [comment]
You haven't sent the journalctl command properly

**Comment by AdityaGarg8** [comment]
You can save it to a file as `journalctl -k --grep=brcmfmac > out.log` and copy and paste the text from there.

**Comment by irenatorosyan** [comment]
Oh, I'm sorry, haven't noticed it's cut off

Nov 29 17:02:20 brleude kernel: usbcore: registered new interface driver brcmfmac
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: enabling device (0000 -> 0002)
Nov 29 17:02:20 brleude kernel: brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4355c1-pcie for chip BCM4355/12
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m-2.5-X0.bin failed with error -2
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m-2.5.bin failed with error -2
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC-m.bin failed with error -2
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-YSBC.bin failed with error -2
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii-X0.bin failed with error -2
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.apple,hawaii.bin failed with error -2
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: Direct firmware load for brcm/brcmfmac4355c1-pcie.bin failed with error -2
Nov 29 17:02:20 brleude kernel: brcmfmac 0000:02:00.0: brcmf_pcie_setup: Dongle setup failed

**Comment by AdityaGarg8** [comment]
```
sudo modprobe -r brcmfmac
sleep 3
sudo modprobe brcmfmac
```

Does this work?

**Comment by irenatorosyan** [comment]
Still no Wi-Fi. Not sure if this is useful information but the Bluetooth does work properly. It may have been working before your help as well, not sure. Just tested it now as the wiki guide or fixing Wi-Fi which I am unable to follow due to the macOS version is also said to fix Bluetooth.

**Comment by AdityaGarg8** [comment]
Bluetooth on your model does not need firmware from macOS

**Comment by AdityaGarg8** [comment]
Can you file a bug report to upstream kernel? The wifi driver is not made by us.

**Comment by irenatorosyan** [comment]
I will open the issue there. Thank you for help!
