### ISSUE TITLE
Bluetooth not working 

### ISSUE THREAD

**Issue by aqw00** [marcosfad/mbp-ubuntu#105]
bluetooth is not working on macbookair 9,1 (6.5.8-t2-jammy)

![Screenshot from 2023-11-30 11-30-29](https://github.com/t2linux/T2-Ubuntu/assets/11737201/cadc7e9f-db5a-4ea3-b44f-6bfc27244f0b)

**Comment by AdityaGarg8** [comment]
This is not kernel.org.
