### ISSUE TITLE
Can't find external nvme hard drive via Thunderbolt/USB4 during install

### ISSUE THREAD

**Issue by liangqi** [marcosfad/mbp-ubuntu#107]
* MacBook Pro 16", 2019 with 4 USB-C Thunderbolt/USB
* v6.6.8-1, a82931f4e96b15959fa873c6b710b48f09e58fa244d5c5c1aa50150afa5fb8ba  ./ubuntu-23.10-6.6.8-t2-mantic.iso

* ORICO M.2 SSD Enclosure TCM2-U4, ASMedia 246x https://oricotechs.com/products/orico-40gbps-usb4-nvme-m-2-ssd-enclosure-with-cooling-fan
* Kingston KC3000 2TB https://www.kingston.com/en/ssd/kc3000-nvme-m2-solid-state-drive

The enclose has USB-A and USB-C, when I use the USB-A with an adapter, it was listed in USB 3 device in macOS, 

ASM246X series:

  Product ID:	0x2463
  Vendor ID:	0x174c  (ASMedia Technology Inc.)
  Version:	1.00
  Speed:	Up to 5 Gb/s
  Manufacturer:	ASMedia
  Location ID:	0x01122000 / 4
  Current Available (mA):	900
  Current Required (mA):	896
  Extra Operating Current (mA):	0

With ubuntu-23.10-6.6.8-t2-mantic.iso in a USB stick, everything works fine.

if I use USB-C directly, it was listed Thunderbolt/USB4 in macOS,

246x:

  Vendor Name:	ASMedia
  Device Name:	246x
  Mode:	Thunderbolt 3
  Device ID:	0x2463
  Vendor ID:	0xB8
  Device Revision:	0xE3
  UID:	0x174C3803DA761800
  Route String:	3
  Firmware Version:	36.19
  Port (Upstream):
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 40Gb/s x1
  Current Link Width:	0x2

With the same USB stick, I can't see the Kingston KC3000 2TB hard drive. How should I continue? Thanks in advance.

**Comment by AdityaGarg8** [comment]
Thunderbolt is more of a hit and miss on Linux. Firstly make sure that the drive is plugged into your Mac before booting Linux. Secondly, try `echo 1 | sudo tee /sys/bus/pci/rescan` after booting Linux, of the drive still doesn't work. Also make sure `pcie_ports=native` is there in the output when you run `cat /proc/cmdline` on Linux.
