### ISSUE TITLE
balenaEtcher cannot accept ubuntu-22.04-6.8.4-t2-jammy.z01 or zip version on MacBook Air 2019

### ISSUE THREAD

**Issue by tommasocalzolari** [marcosfad/mbp-ubuntu#111]
I've also tried using USBImager or the dd command on terminal. Both balenaEtcher and USBImager don't accept the files and the dd command lets me install the ISO into the USB but when I restart and press option the orange bootable EFI is not there.

**Comment by AdityaGarg8** [comment]
> I've also tried using USBImager or the dd command on terminal. Both balenaEtcher and USBImager don't accept the files and the dd command lets me install the ISO into the USB but when I restart and press option the orange bootable EFI is not there.

Did you run iso.sh? Please read the instructions.
