### ISSUE TITLE
t2-linux

### ISSUE THREAD

**Issue by palanza** [marcosfad/mbp-ubuntu#125]
hi,

i need offline deb package for t2-linux or t2-linux-tls
where can find a direct url ?

tnx

**Comment by AdityaGarg8** [comment]
> hi,
> 
> i need offline deb package for t2-linux or t2-linux-tls where can find a direct url ?
> 
> tnx

You want ISO or kernel? The issue you have posted is on the ISO repo.

**Comment by alex-007** [comment]
you can find them from here https://github.com/t2linux/T2-Debian-and-Ubuntu-Kernel/releases
