### ISSUE TITLE
LVM with LUKS encryption drops you to a rescue shell post install

### ISSUE THREAD

**Issue by AlvaretA** [marcosfad/mbp-ubuntu#130]
Hello! I come directly from the t2linux discord with a bug report.

**Symptom**
Post install with LVM and LUKS FDE drops you on a busybox rescue shell

**Steps to reproduce**

1. Boot from noble t2linux ubuntu ISO (Tried on both a MacBookPro 16,1 and a MacBookPro15,1).
2. When installing, select the option to use LVM and then select the Full Disk Encryption option that enables after. Selecting "Overwrite unused disk space" shouldn't affect the output.
3. Install it
4. Reboot
5. Select the Ubuntu EFI Boot option on the boot picker
6. After plymouth, you should be dropped to a ubuntu busybox rescue shell with (initramfs) appended to the line.

I'm available on Discord for further discussion, but will follow here for a response as well. Thank you in advance!

**Comment by AdityaGarg8** [comment]
Issue on Ubuntu's side imo.
