### ISSUE TITLE
Endeavour OS on Macbook Air 2020

### ISSUE THREAD

**Issue by wmrose** [marcosfad/mbp-ubuntu#133]
Wifi will not connect.  Journalctl shows "NetworkManager [559]: <warn> [1727127846.1600] platform-linux: do-change-link[2]: failure 12 (cannot allocate memory)
and
...device (wlan0): sethw-addr: failed to set MAC address...

Drivers seem to be where they belong, in /lib/firmware/brcm

Different computer or I'd paste output.

Thanks, Bill

**Comment by AdityaGarg8** [comment]
This is an issue with Endeavour OS, so please open it in their repo. This repo is for Ubuntu.

**Comment by AdityaGarg8** [comment]
https://github.com/t2linux/EndeavourOS-ISO-t2

**Comment by wmrose** [comment]
Sorry!  For what it's worth, although NMCLI doesn't work, it turns out that IWC does.  Could be helpful with your distro, too.  Found on Prohoster.info's blog.

**Comment by NoaHimesaka1873** [comment]
@wmrose That's a pretty well-known issue, affecting *all* Broadcom devices, caused by newest version of wpa_supplicant.

**Comment by AdityaGarg8** [comment]
> Sorry! For what it's worth, although NMCLI doesn't work, it turns out that IWC does. Could be helpful with your distro, too. Found on Prohoster.info's blog.

I believe you are facing the infamous wpa_supplicant regression issue. Fortunately Ubuntu isn't affected yet since it uses the older version of wpa_supplicant
