### ISSUE TITLE
Wi-Fi can't connect to the network with 'WPA3-PSK' security

### ISSUE THREAD

**Issue by Rom888** [marcosfad/mbp-ubuntu#139]
Wifi can't connect to the wifi network with the 'WPA3-PSK' security setting on the router and the macbook.
Wifi can connect only if I set 'WPA2-PSK + WPA3-PSK' on the router and 'WPA & WPA2 Personal' on the macbook.

It worked before the fresh upgrade from Ubuntu 23.10 to Ubuntu 24.04.
It also works with the same Wi-Fi network on another Asus computer with Ubuntu 24.04.

I used firmware.sh from here:
https://wiki.t2linux.org/guides/wifi-bluetooth/
method 4 (obtaining the firmware directry from macOS)

My machine:
```
macOs: Ventura 13.2

Ubuntu 24.04
v6.12.4-1

MacBookPro16.1
Intel Core i9 2.3g

hybrid graphics:
Intel UHD graphics 630
AMD radeon pro 5500M
```

**Comment by AdityaGarg8** [comment]
> Wifi can't connect to the wifi network with the 'WPA3-PSK' security setting on the router and the macbook. Wifi can connect only if I set 'WPA2-PSK + WPA3-PSK' on the router and 'WPA & WPA2 Personal' on the macbook.
> 
> It worked before the fresh upgrade from Ubuntu 23.10 to Ubuntu 24.04. It also works with the same Wi-Fi network on another Asus computer with Ubuntu 24.04.
> 
> I used firmware.sh from here: https://wiki.t2linux.org/guides/wifi-bluetooth/ method 4 (obtaining the firmware directry from macOS)
> 
> My machine:
> 
> ```
> macOs: Ventura 13.2
> 
> Ubuntu 24.04
> v6.12.4-1
> 
> MacBookPro16.1
> Intel Core i9 2.3g
> 
> hybrid graphics:
> Intel UHD graphics 630
> AMD radeon pro 5500M
> ```

WPA3 doesn't work for now. Use WPA2
