### ISSUE TITLE
No wifi after installation

### ISSUE THREAD

**Issue by Jynra** [marcosfad/mbp-ubuntu#140]
Hello,
Even after installation I can't connect the wifi. There is only the wired option.
And I don't have the touchbar either.
Is there an additional installation to do ?

**Comment by AdityaGarg8** [comment]
Did you run the firmware script for wifi?

For touchbar, did you install tiny-dfr or are using basic mode?

**Comment by Jynra** [comment]
> Did you run the firmware script for wifi?
> 
> For touchbar, did you install tiny-dfr or are using basic mode?

During installation I selected “install third-party software for graphics and wi-fi hardware”.
Is there an extra step after reboot ?
What is and where is the firmware script for wifi ?
I didn't install tiny-dfr, it's not indicated anywhere in the T2linux procedure.

**Comment by AdityaGarg8** [comment]
> > Did you run the firmware script for wifi?
> > For touchbar, did you install tiny-dfr or are using basic mode?
> 
> During installation I selected “install third-party software for graphics and wi-fi hardware”. Is there an extra step after reboot ? What is and where is the firmware script for wifi ? I didn't install tiny-dfr, it's not indicated anywhere in the T2linux procedure.

https://wiki.t2linux.org/distributions/ubuntu/installation/#setting-up-wi-fi-and-bluetooth

I believe you didn't follow this guide.

**Comment by AdityaGarg8** [comment]
For touchbar, share `lsusb`

**Comment by Jynra** [comment]
Thank you
I didn't read the right guide.
problems solved for the wifi and touchbar.
