### ISSUE TITLE
Track-pad occasionally freezes 

### ISSUE THREAD

**Issue by acheong08** [marcosfad/mbp-ubuntu#54]
When using the track pad, it sometimes just stops moving. Not sure if this has happened back in MacOS, could just be that there is something wrong with my fingers.

**Comment by Redecorating** [comment]
Are you using the camera at the same time? When the camera is used it can saturate apple-bce's bandwidth (as the linux implementation is slower than the macOS one), which can make the trackpad jittery

**Comment by acheong08** [comment]
No, I am not. However, the issue appears to be fixed when my hands get warmed up. This is probably a hardware issue rather than ubuntu.
