### ISSUE TITLE
rEFInd doesn't see the external drive image

### ISSUE THREAD

**Issue by JetForMe** [marcosfad/mbp-ubuntu#78]
The official 22.04 installer shows up, but your safe graphics one does not. I've tried flashing it twice. Is there anything I can do?

**Comment by Redecorating** [comment]
Does the safe graphics installer ISO show up in apple's boot manager (the one you get by holding down the option key when you turn the power on)? It might be an issue with how refind discovers boot options, not an issue with the contents of the USB.

**Comment by AdityaGarg8** [comment]
You need to boot the drive using the startup manager.

**Comment by JetForMe** [comment]
Ah, interesting. Holding down Option gives three choices: The macOS partition, and two `EFI Boot` options. I don’t know which is which. I chose the first, and after an Apple logo and some screen flashes, a macOS alert appeared saying it needed a software update, with buttons for “Startup Disk…” and “Update.” As this machine has 13.0.1 on it, I decided to let the update happen. We’ll see where this goes.



> You need to boot the drive using the startup manager.

@AdityaGarg8 Is this what you get with Option held down, or is that something else?

**Comment by JetForMe** [comment]
So, the second EFI image seemed to be the right one. Sorry to co-opt this ticket, but what is "NVMe Blacklisting?" I can find lots of google results for how to do it, but I don't know *why* I'd want to do that.

**Comment by AdityaGarg8** [comment]
> So, the second EFI image seemed to be the right one. Sorry to co-opt this ticket, but what is "NVMe Blacklisting?" I can find lots of google results for how to do it, but I don't know _why_ I'd want to do that.

Some users want to install on an external drive. Blacklisting nvme hides the internal SSD during installation. I did that since the installer is crappy as far as installing on external drives in concerned. Although, not a very effective way since the external drive could also be nvme.

**Comment by JetForMe** [comment]
Ah okay. I'm glad I didn't choose that one then, since I was installing on a partition on the internal drive.
