### ISSUE TITLE
Trackpad doesn't work on MacBookPro16,4 install

### ISSUE THREAD

**Issue by JetForMe** [marcosfad/mbp-ubuntu#79]
I was able to use the keyboard to navigate through the install, but it wasn't until after the installed OS booted and I attached an external mouse that I was able to get mouse control. At that point the trackpad started to work. I did not try attaching an external mouse during the install phase.

**Comment by AdityaGarg8** [comment]
Whatever you wrote is too confusing for me. Could you please be more clear.

**Comment by JetForMe** [comment]
The trackpad didn't work all throughout the graphical install of Ubuntu. There was no visible pointer and clicking did nothing.

I was able to use the keyboard to navigate through and complete the install.

After that, the trackpad still didn't work.

I plugged in an external mouse, which caused a pointer to appear, and the trackpad to work.

**Comment by AdityaGarg8** [comment]
Currently the trackpad works right? Are you able to reproduce the issue on your current installation?

**Comment by JetForMe** [comment]
Yes, it works (although not very well, but that's another story). I'm just saying it didn't work until I plugged in a mouse. I haven't tried to reproduce it (a proper repro would require installing Ubuntu all over again.).

**Comment by AdityaGarg8** [comment]
That's fine then
