### ISSUE TITLE
Link typo in the documentation

### ISSUE THREAD

**Issue by Nuxar1** [marcosfad/mbp-ubuntu#80]
Hey, i'm not sure if this is the correct repo for this issue, sorry in advance.

On https://wiki.t2linux.org/distributions/ubuntu/home/ there is a typo in the link to the installation guide.
It's https://wiki.t2linux.org/distributions/ubuntu//installation/ (2 slashes) but should be https://wiki.t2linux.org/distributions/ubuntu/installation/.
This causes the linked page to not display properly.

**Comment by AdityaGarg8** [comment]
Hi

I've fixed the link. Thanks for reporting!
