### ISSUE TITLE
HDMI over USB-C

### ISSUE THREAD

**Issue by qume** [marcosfad/mbp-ubuntu#97]
I have a 2019 Macbook Air, and have tried three different USB-C to HDMI (or DisplayPort) adapters (passthrough / alt mode, not displaylink). None of them work, and regardless of whether they are plugged in or not, xrandr gives the following output:
```
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
```

All of these work under MacOS.

Running the latest Lunar kernel

**Comment by lemmyg** [comment]
Hello,
I would suggest to ask directly in the discord forum.
it could be related to a limitation in the gpu drivers.
https://discord.com/channels/595304521857630254/596303447033249822
