### ISSUE TITLE
After burning iso unto usb drive mac return error: `The disk you attached was not readable by this computer`

### ISSUE THREAD

**Issue by Tropical-Smootie** [marcosfad/mbp-ubuntu#98]
I used the iso.sh file to download the ubuntu-22.04-6.4.8-t2-jammy.iso
After, i used both Balena Etcher and the `dd` command to burn the iso unto a usb drive that i used formated to MS-DOS(FAT)

But after every try it returns the error: `The disk you attached was not readable by this computer`

is anyone else experiencing this issue?

**Comment by AdityaGarg8** [comment]
It's normal, you'll be able to boot it from startup manager

**Comment by Tropical-Smootie** [comment]
> It's normal, you'll be able to boot it from startup manager 

How come i didnt get that warning when i burned the iso from the ubuntu official website?

**Comment by AdityaGarg8** [comment]
I have no idea in this tbh but for some reason the custom ISOs show this error
